# -*- coding: utf-8 -*-
"""chatbot_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIvjQMi4Mg534WCYy2SKi7wEP1sOvQND
"""

!pip install flask pyngrok

import json

# Create a chatbot JSON file with sample responses
chatbot_data = {
    "hello": "Hi there! How can I help you?",
    "how are you": "I'm just a bot, but I'm doing great! How about you?",
    "bye": "Goodbye! Have a great day!"
}

# Save to a file
with open("chatbot_data.json", "w") as file:
    json.dump(chatbot_data, file)

from flask import Flask, request, jsonify
from pyngrok import ngrok

# Initialize Flask app
app = Flask(__name__)

# Ngrok Authentication (Replace with your actual auth token)
NGROK_AUTH_TOKEN = "2tJoe6muWRnzrI6E7QudfKHN6nv_7RQcBXYNuidg8RZLzeFyu"  # Replace with your actual token
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Start Ngrok tunnel
public_url = ngrok.connect(5000).public_url
print(f"Public URL: {public_url}")

# ✅ Add a default route to prevent 404 error
@app.route("/")
def home():
    return "Welcome to the Chatbot API! Use /chatbot?message=your_message"

# Chatbot API
@app.route("/chatbot", methods=["GET"])
def chatbot():
    user_message = request.args.get("message", "")
    response = {"response": f"You said: {user_message}"}
    return jsonify(response)

if __name__ == "__main__":
    app.run(port=5000)